### ISSUE TITLE
static methods are not copied on "BuiltIn" in legacy mode

### ISSUE THREAD

**Issue by kapouer** [WebReflection/custom-elements-builtin#4]
hi,

on webkitgtk 2.30 (safari-like) with @ungap/custom-elements@0.1.9

```
class MyCustomElement extends HTMLElement {
  static mystatic() {}
}
```
later `MyCustomElement.mystatic` is undefined, and
```
MyCustomElement
function HTMLBuiltIn() {...    custom-elements.js:419
```

This used to work when i used document-register-element with @ungap/custom-elements-builtin.

**Comment by kapouer** [comment]
Also note that doing
```
MyCustomElement.mystatic = function() {}
```
gives the same result, the mystatic method is pruned.

**Comment by WebReflection** [comment]
This bug is confusing, to say the least ...

 > `class MyCustomElement extends HTMLElement`

this module is for custom elements **builtin** and nothing changes with regular custom elements

> This used to work when i used document-register-element with @ungap/custom-elements-builtin.

`document-register-element` already provides builtin extends, that combo doesn't look right

> MyCustomElement.mystatic = function() {}

... I've just tried on GNOME Web without anything around this code:

```js
class MyCustomElement extends HTMLElement {
  static mystatic() {}
}
customElements.define('what-ever', MyCustomElement);
customElements.get('what-ever').mystatic();
```

no issues ... now I went to the [test page](https://webreflection.github.io/custom-elements-builtin/test/) and copy pasted the same thing ... no issue.

The README also writes https://github.com/WebReflection/custom-elements-builtin#update

**Do not use this module directly**

but regardless, you have filed a bug to a module that has nothing to do with custom elements without builtin extends and your very same example code works in WebKit and Safari mobile, hence I'm closing this until further, better, details, are provided.

Bear in mind: if you are using transpilers, including TypeScript, I won't solve **their** issues, 'cause those don't belong in here.

**Comment by kapouer** [comment]
Sorry for that. For the record i'm not using the module directly. The issue i'm seeing surely comes from a mistake on my side, so thank you for the clarification.

**Comment by kapouer** [comment]
My mistake was that i did not actually use MyCustomElement: i used "HTMLCustomElement" and declared it on the global scope. I renamed it to something else and voilà.

**Comment by WebReflection** [comment]
glad you found the culprit of your issue 👍
